### ISSUE TITLE
Add a path option

### ISSUE THREAD

**Issue by razzeee** [verdammelt/mix_npm#1]
So from my understanding, this will only work if the `package.json` is in your top level folder.

Mine for example is in  `assets` (phoenix), so I need to traverse to that folder first.

**Comment by verdammelt** [comment]
Sorry for the late response. When I wrote this code I thought I might be doing some Elixir work. That never happened. So it was a nice learning experience - but not a living project.

If you have create a PR for it I'll happily review and (probably) merge it.

**Comment by razzeee** [comment]
I ended up doing this without your package

**Comment by verdammelt** [comment]
@Razzeee OK, good, glad you weren't stuck waiting for me.
